# Description: This workflow runs OpenRewrite recipes against opened pull request and upload the patch.
# Since this pull request receives untrusted code, we should **NOT** have any secrets in the environment.
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
---
name: create-pr-suggestions

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  create-suggestions:
    runs-on: ubuntu-latest
    env:
      # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Execute recipes
      - name: Apply OpenRewrite recipes
        run: mvn --activate-profiles apply-orbest-practices verify

      # Post suggestions as a comment on the PR
      - uses: googleapis/code-suggester@v4
        with:
          command: review
          pull_number: ${{ github.event.number }}
          git_dir: '.'
